FROM node:22.18.0-alpine3.21

RUN apk add --update --no-cache curl git wget && rm -rf /var/cache/apk/*


WORKDIR /app/server

COPY ./dist/apps/www/browser /app/next
COPY ./dist/apps/www/server /app/server

RUN echo ${COMPOSE_HOSTNAME} on loglevel ${COMPOSE_LOGGER}

HEALTHCHECK --interval=15s --timeout=5s \
  CMD wget -q --spider http://127.0.0.1:80/_health >/dev/null 2>&1

EXPOSE 80

COPY ./docker/ssr-entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

CMD ["./entrypoint.sh"]
